# -*- coding: utf-8 -*-
"""BM25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1408RFBOvfPVxG9SKGu8EsQ7hcV4uRODo

## Import
"""

!pip install rank_bm25

import numpy
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
import os
import string
from collections import OrderedDict
import zipfile
from random import shuffle
from random import seed
import math
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from rank_bm25 import BM25Okapi
import pandas as pd
#import cosine_ranking as cr

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')

"""## Preprocess"""

#The pos tags given from the pos_tag function in preprocess were simplified by making our own pos_tagger function. 
def pos_tagger(nltk_tag):
	if nltk_tag.startswith('J'):
		return wordnet.ADJ
	elif nltk_tag.startswith('N'):
		return wordnet.NOUN
	elif nltk_tag.startswith('R'):
		return wordnet.ADV
	elif nltk_tag.startswith('V'):
		return wordnet.VERB
	else:		
		return None

#Preprocessing taken from assignment 1
def preprocess(textfile):
  textfile = textfile.lower() #convert to lowercase

  string_encode = textfile.encode("ascii", "ignore")  #removing unicode characters
  textfile = string_encode.decode()
  
  translator = str.maketrans('', '', string.punctuation) #remove punctuation
  textfile = textfile.translate(translator)

  textfile = " ".join(textfile.split()) #remove whitespace

  word_tokens = word_tokenize(textfile) #tokenize

  stop_words = set(stopwords.words("english")) #remove stopwords
  textfile = [word for word in word_tokens if word not in stop_words]

  lemmatizer = WordNetLemmatizer() # lemmatization
  lemmatized_sentence = []
  pos_tagged = nltk.pos_tag(textfile)
  #print(pos_tagged)
  wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
  #print(wordnet_tagged)
  for word, tag in wordnet_tagged:
    if tag is None:
      lemmatized_sentence.append(word) # if no available tag then append the token as is
    else:	
      lemmatized_sentence.append(lemmatizer.lemmatize(word, tag)) # else lemmatize the token using the tag
  textfile=lemmatized_sentence

  return textfile
preprocess("Hello-my name      is 3 sam's looked \u200c books. Hi bÿíûump. This is for a sample sentence and we are going to remove the stopwords from this.")

"""## BM25 Model"""

def rerank(query,topk, tokenized_corpus, df):
  #preprocess the query
  tokenized_query = preprocess(query)
  print(tokenized_query)

  #k1 and b are parameters for our bm25 model
  k1 = 0.75
  b = 0.05

  bm25 = BM25Okapi(corpus = tokenized_corpus, k1=k1,b=b)
  
  #get the score for each document
  doc_scores = bm25.get_scores(tokenized_query)
  #print(doc_scores)

  #add the score of each document in the dataframe and sort in desceding order. Greater the score, greater the relevance
  tempdf = df.copy()
  tempdf['bm25score'] = doc_scores
  tempdf = tempdf.sort_values(by ='bm25score', ascending = 0)
  return tempdf.head(topk)

"""## Recommend articles"""

df = pd.read_csv('IRdata_Resource.csv')  
corpus = df['text'].tolist() 

#tokenized_corpus is a list of list of strig. Each element in the list represents a document, and each document is a list of the terms.
tokenized_corpus = []
for doc in corpus:
  tokenized_corpus.append((preprocess(doc)))
#print(tokenized_corpus)

def recommend_articles(query,k):
  global tokenized_corpus
  global df
  ans_df = rerank(query,k, tokenized_corpus, df)
  #print(ans_df)
  return ans_df['link'].tolist()

# recommend_articles("Identify the correct formula for the carbohydrate rhamnose? Biomolecules Carbohydrates 1", tokenized_corpus, df)
recommend_articles("Which compound reacts with propene to form tripropyl borane? Alcohols, Phenols & Ethers Alcohols & Phenols - 1",3)