# -*- coding: utf-8 -*-
"""Copy of FinalDatasetChemistry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LzzHHsnYnwBzkWZ0BquCtRrZSEK_ui21
"""

import numpy as np 
import pandas as pd 
import requests 
from bs4 import BeautifulSoup
import re

def cleanString(curString):
  replace_list = ['<p>', '<br/>', '<br>', '</p>']
  for cur_word in replace_list:
    curString = curString.replace(cur_word, '')
  curString = re.sub('^(.\) )', '', curString)
  curString = re.sub('^(.{1,2}\. )', '', curString)
  return curString

def get_columns(link):
  webObject = requests.get(link).text 
  soupObject = BeautifulSoup(webObject, 'html.parser')
  questionsSection = soupObject.find("div", {"class":"entry-content"}, {"type":"regular"})
  questionsDivs = questionsSection.find_all("span", {"class":"collapseomatic"}, {"type":"regular"})
  questionsRaw = [[] for i in range(len(questionsDivs))]
  for i in range(len(questionsDivs)):
    txt = str(questionsDivs[i].parent).splitlines()
    for l in txt:
      if "collapseomatic" in l:
        break
      questionsRaw[i].append(l)
  
  options = [[] for i in range(len(questionsDivs))]
  images  = [0 for i in range(len(questionsDivs))]
  for i in range(len(questionsRaw)):
    for j in range(len(questionsRaw[i])):
      if bool(re.match(r"^(<p>.{1,2}\. )", questionsRaw[i][j])):
        continue
      if bool(re.match(r"^(<a href=)", questionsRaw[i][j])):
        images[i] = re.findall('(?:(?:https?|ftp):\/\/)?[\w/\-?=%.]+\.[\w/\-&?=%.]+', questionsRaw[i][j])[0]
        continue 
      options[i].append(cleanString(questionsRaw[i][j]))
  
  questions = []
  answers = []
  explainations = []
  reQues = re.compile(r'^(<p>.{1,2}\. )')
  reAns = re.compile(r'Answer:')
  reExp = re.compile(r'Explanation:')
  for l in str(questionsSection).splitlines():
    if reQues.search(l):
      questions.append(cleanString(re.sub('^(<p>.{1,2}\. )', '', l)))
    if reAns.search(l):
      temp = re.findall('Answer: .', l)[0]
      answers.append(temp[-1])
    if reExp.search(l):
      explainations.append(cleanString(l).replace('Explanation: ', ''))

  return questions, options, images, answers, explainations

def get_links(link):
  kk = requests.get(link).text 
  soup=BeautifulSoup(kk, 'html.parser')

  domainList = soup.find("div", {"class":"sf-postw-category"}, {"type":"regular"})
  domains = []
  for x in domainList.find_all('span'):
    domains.append(x.text)

  subDomains = [[] for i in range(len(domains))]
  subDomainLinks = [[] for i in range(len(domains))]

  domainCount = 0
  for x in domainList.find_all('div', {"class":"collapseomatic_content"}, {"type":"regular"}):
    children = x.findChildren("a" , recursive=True)
    for c in children:
      subDomains[domainCount].append(c.text)
      subDomainLinks[domainCount].append(c['href'])
    domainCount += 1
  return domains, subDomains, subDomainLinks

def get_questions(domains, subDomains, subDomainLinks, subject):
  q = []
  for i in range(len(domains)):
    for j in range(len(subDomains[i])):
      questions, options, images, answers, explainations = get_columns(subDomainLinks[i][j])
      n = len(questions)
      for k in range(n):
        q.append([subject, domains[i], subDomains[i][j], questions[k], images[k], options[k], answers[k], explainations[k]])
  return q

q = []
domains, subDomains, subDomainLinks = get_links('https://www.sanfoundry.com/chemistry-multiple-choice-questions-iit-jee-exam/')
q.extend(get_questions(domains, subDomains, subDomainLinks, 'chemistry'))
domains, subDomains, subDomainLinks = get_links('https://www.sanfoundry.com/mathematics-questions-answers-types-relations/')
q.extend(get_questions(domains, subDomains, subDomainLinks, 'mathematics'))

df = pd.DataFrame(q, columns = ['subject', 'domain', 'subdomain', 'question', 'imageURL', 'options', 'answer', 'explaination'])
df.index.name = 'QID'

df

from google.colab import drive
drive.mount('drive')

df.to_csv('IRdata3.csv')
!cp IRdata3.csv "drive/My Drive/"

print(len(df['domain'].unique()))